### ISSUE TITLE
runtime crashes while executing the ResNet example

### ISSUE THREAD

**Issue by Flipfle** [abejgonzalez/nvdla-workload#6]
I want to test the given ResNet50 example with Firemarshal in Chipyard. 

I installed everything probably like described in the docs of Chipyard and Firemarshal.

I executed in firemarshal directory
```
./marshal -v -d  build ../nvdla-workload/marshal-configs/nvdla-large-resnet50.json 
./marshal -v -d launch ../nvdla-workload/marshal-configs/nvdla-large-resnet50.json
```

The image is built errorless and the openSBI starts. When it trys to execute `./nvdla_runtime --loadable resnet50_large.nvdla --image dog.jpg` it throws:
```
creating new runtime context...
libnvdla<1> failed to open dla device
libnvdla<1> Out of bounds DLA instance 0 requested.
(DLA_TEST) Error 0x00000004: runtime->load failed (in RuntimeTest.cpp, function loadLoadable(), line 354)
(DLA_TEST) Error 0x00000004: (propagating from RuntimeTest.cpp, function run(), line 444)
(DLA_TEST) Error 0x00000004: (propagating from main.cpp, function launchTest(), line 87)
```

I think it may be because `insmod /usr/share/opendla.ko` is not started probably because it does not return something like:
```
[   34.684558] opendla: loading out-of-tree module taints kernel.
[   34.700807] reset engine done
[   34.713180] [drm] Initialized nvdla 0.0.0 20171017 for 10200000.nvdla on minor 0
```
Recording to NVDLA/VP this should be the output after the command I think.
Why is it not necessary to execute a `insmod drm.ko` like in the NVDLA/VP?

So I am new to this subject it could be that I miss something. Can anyone help me?

**Comment by raspberry4B** [comment]
hey, I have the same problem, did you solve it

**Comment by Flipfle** [comment]
No I haven't. We executed it on an FPGA and there it worked. I believe the simulation with marshal doesn't work somehow.

**Comment by abejgonzalez** [comment]
FireMarshal doesn't have a NVDLA model in QEMU/Spike (what is used for the `launch` command). Therefore, this repo will only work with RTL simulation.

**Comment by Yuxin-Yu** [comment]
Hello, I also display "failed to open dla device" when I execute it in FPGA. At present, I guess it is the problem of Linux image. How do you generate your Linux image? @Flipfle

**Comment by rookie0620** [comment]
How do you generate your linux image? I even can`t generate an image that can boot on FPGA. How do you select boards,firechip or prototype? If I choose prototype, error occurs in config.py. Howerver, If I choose firechip, I can`t boot the image on FPGA @Yuxin-Yu

**Comment by Yuxin-Yu** [comment]
Hi, @rookie0620 .I met the same problem when I generate nvdla image.When I select boards with prototype,I got there error
```
Traceback (most recent call last):
  File "/home/yyx/riscv/projects/chipyard/software/firemarshal/wlutil/config.py", line 696, in __init__
    self._initializeFromBase(self.cfgs[cfgName])
  File "/home/yyx/riscv/projects/chipyard/software/firemarshal/wlutil/config.py", line 795, in _initializeFromBase
    self._initializeFromBase(baseCfg)
  File "/home/yyx/riscv/projects/chipyard/software/firemarshal/wlutil/config.py", line 797, in _initializeFromBase
    cfg.applyBase(baseCfg)
  File "/home/yyx/riscv/projects/chipyard/software/firemarshal/wlutil/config.py", line 549, in applyBase
    inheritLinuxOpts(self.cfg, baseCfg)
  File "/home/yyx/riscv/projects/chipyard/software/firemarshal/wlutil/config.py", line 355, in inheritLinuxOpts
    for name, src in list(config['linux']['modules'].items()):
KeyError: 'modules'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yyx/riscv/projects/chipyard/software/firemarshal/./marshal", line 236, in <module>
    main()
  File "/home/yyx/riscv/projects/chipyard/software/firemarshal/./marshal", line 113, in main
    cfgs = wlutil.ConfigManager(args.config_files, list(workdirs.keys()))
  File "/home/yyx/riscv/projects/chipyard/software/firemarshal/wlutil/config.py", line 698, in __init__
    raise WorkloadConfigError(cfgName,
wlutil.config.WorkloadConfigError: Unable to load workload nvdla-small-resnet50.json: Missing required option 'modules'
```
Have you solve this problem?

**Comment by Yuxin-Yu** [comment]
Hi @Flipfle @abejgonzalez .Could you tell me how can I get drm.ko file for risc-v linux image?
