### ISSUE TITLE
Build image failed

### ISSUE THREAD

**Issue by Yuxin-Yu** [abejgonzalez/nvdla-workload#8]
Hi, I have successfully generated Linux image and started LInux in FPGA following the tutorial of VCU118, but when I used Marshal to generate the LInux image of nvdla, there was an error:

> [ICer@IC_EDA /home/ICer/riscv/projects/chipyard/software/firemarshal]$./marshal -v build ../nvdla-workload/marshal-configs/nvdla-small-resnet50.json 
> sudo: a password is required
> DEBUG: Loading nvdla-small-resnet50.json:/home/ICer/riscv/projects/chipyard/software/nvdla-workload/marshal-configs/nvdla-small-resnet50.json
> DEBUG: Creating distro br : 5244
> Traceback (most recent call last):
>   File "/home/ICer/riscv/projects/chipyard/software/firemarshal/wlutil/config.py", line 696, in __init__
>     self._initializeFromBase(self.cfgs[cfgName])
>   File "/home/ICer/riscv/projects/chipyard/software/firemarshal/wlutil/config.py", line 795, in _initializeFromBase
>     self._initializeFromBase(baseCfg)
>   File "/home/ICer/riscv/projects/chipyard/software/firemarshal/wlutil/config.py", line 797, in _initializeFromBase
>     cfg.applyBase(baseCfg)
>   File "/home/ICer/riscv/projects/chipyard/software/firemarshal/wlutil/config.py", line 549, in applyBase
>     inheritLinuxOpts(self.cfg, baseCfg)
>   File "/home/ICer/riscv/projects/chipyard/software/firemarshal/wlutil/config.py", line 355, in inheritLinuxOpts
>     for name, src in list(config['linux']['modules'].items()):
> KeyError: 'modules'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "./marshal", line 228, in <module>
>     main()
>   File "./marshal", line 113, in main
>     cfgs = wlutil.ConfigManager(args.config_files, list(workdirs.keys()))
>   File "/home/ICer/riscv/projects/chipyard/software/firemarshal/wlutil/config.py", line 699, in __init__
>     extra=f"Missing required option '{e.args[0]}'")
> wlutil.config.WorkloadConfigError: Unable to load workload nvdla-small-resnet50.json: Missing required option 'modules'

How can I fix it,Thank you!

**Comment by rookie0620** [comment]
Do you fix this problem now？Encountered the same issue with you.

**Comment by Yuxin-Yu** [comment]
Hi @rookie0620 yes,I hava fixed this probleam,which like:https://github.com/ucb-bar/chipyard/issues/1558
